### ISSUE TITLE
Ctrl not working as toMods

### ISSUE THREAD

**Issue by orkhan10** [elliotwaite/hammerspoon-config#2]
Hey Elliot. First of all, a HUGE Thank you. Left cmd and arrow shortcuts are genius!

I wanted to extend them to use ctrl as well:
```
  {'leftCmd+leftCtrl', 'j', 'ctrl', 'left'},
  {'leftCmd+leftCtrl', 'l', 'ctrl', 'right'},
```
But it does not work.

the problem is with the 'ctrl' . It is not recognized for some reason.
-----
As I had encountered this problem I tried implementing these shortcuts in Karabiner-Elements. First I was very happy as I did not need to define each of them one by one. 

Then I encountered a very weird problem, which I have described here:
https://github.com/pqrs-org/Karabiner-Elements/issues/2666

-----

If you could take a look at these, I'd really appreciate it.
It is like I hit a wall from both sides.

( Edit: OMG, you are behind the new youtube rating extension as well?? You are a legend!! )

**Comment by orkhan10** [comment]
I just tried the solution of issue #1 
It also did not work
```
keyDownWatcher = hs.eventtap.new({hs.eventtap.event.types.keyDown}, function(event)
  if modStates[55] and modStates[59] and event:getKeyCode() == hs.keycodes.map['j'] then
    return true, hs.eventtap.keyStroke('ctrl', 'left', 0)
  end
end):start()

keyDownWatcher = hs.eventtap.new({hs.eventtap.event.types.keyDown}, function(event)
  if modStates[55] and modStates[59] and event:getKeyCode() == hs.keycodes.map['l'] then
    return true, hs.eventtap.keyStroke('ctrl', 'right', 0)
  end
end):start()
```

**Comment by elliotwaite** [comment]
Strange, both versions seem to work for me. Both this version:
``` 
{'leftCmd+leftCtrl', 'j', 'ctrl', 'left'},
```
And this one:
```
keyDownWatcher = hs.eventtap.new({hs.eventtap.event.types.keyDown}, function(event)
  if modStates[55] and modStates[59] and event:getKeyCode() == hs.keycodes.map['j'] then
    return true, hs.eventtap.keyStroke('ctrl', 'left', 0)
  end
end):start()
```
However, there is an error in your second example that may be causing an issue. You are assigning both event tap objects to the save variable, `keyDownWatcher`. You should instead assign each to its own variable, for example `keyDownWatcher1` and `keyDownWatcher2`, or `cmdCtrlLeftKeyDownWatcher` and `cmdCtrlRightKeyDownWatcher`. The variable names are arbitrary, but they need to be unique. The reason that they each need to be assigned to a unique global variable is that once the event tap object returned by the call to `hs.eventtap.new()` goes out of scope, the object will eventually get garbage collected and will no longer capture events. And how long it takes to get garbage collected is variable, so it might start out working for some amount of time, but then later stop working when it eventually gets garbage collected. So in your example code, when you make your second assignment to `keyDownWatcher = ...`, it will make the first event tap object no longer be referenced from the global scope so it will eventually get garbage collected.

Let me know if changing the code to something like this helps at all:
```
cmdCtrlLeftKeyDownWatcher = hs.eventtap.new({hs.eventtap.event.types.keyDown}, function(event)
  if modStates[55] and modStates[59] and event:getKeyCode() == hs.keycodes.map['j'] then
    return true, hs.eventtap.keyStroke('ctrl', 'left', 0)
  end
end):start()

cmdCtrlRightKeyDownWatcher = hs.eventtap.new({hs.eventtap.event.types.keyDown}, function(event)
  if modStates[55] and modStates[59] and event:getKeyCode() == hs.keycodes.map['l'] then
    return true, hs.eventtap.keyStroke('ctrl', 'right', 0)
  end
end):start()
```

P.S. - Sorry for taking so long to reply to this. I just found out I haven't been receiving GitHub notifications. This should be fixed now.

**Comment by elliotwaite** [comment]
I'm going to close this issue since I haven't heard a reply in a while. But feel free to let me know if I should reopen this issue if it is still unresolved.
